# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  admin_user: $(adminUser)
  admin_pass: $(adminPass)
  vm_name: $(vmName)
  v_net: $(vNet)
  sub_net: $(subNet)


trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: CopyFiles@2
  inputs:
    SourceFolder: '.'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: $(azConnection)
    subscriptionId: $(subId)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(resGroup)
    location: 'uksouth'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.parameters.json'
    overrideParameters: ' -vmName $(vm_name) -adminUserName $(admin_user) -adminPasswordOrKey $(admin_pass) -virtualNetworkName $(v_net) -subnetName $(sub_net)'
    deploymentMode: 'Incremental'
