# Deploy a Linux VM into Azure

variables:
  # Azure Resource Manager Connection
  AZ_CONN: $(azConnection)
  SUB_ID: $(subId)
  RES_GROUP: $(resGroup)

  # Admin Username
  ADMIN_USER: $(adminUser)
  
  # adminAuthType should be sshPublicKey or password, and adminAuth should contain the credential
  ADMIN_AUTH: $(adminAuth)
  ADMIN_AUTH_TYPE: $(adminAuthType)

  # Name of the Virtual machine
  VM_NAME: $(vmName)

  # Virtual Network Settings
  V_NET: $(vNet)
  V_NET_PREFIX: $(vNetPrefix)
  SUB_NET: $(subNet)
  SUB_NET_PREFIX: $(subNetPrefix)
  DNS_PREFIX: $(dnsLabelPrefix)
  
  # Deploy the Virtual network (true or false)?
  DEPLOY_VNET: $(deployVnet)

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: CopyFiles@2
  inputs:
    SourceFolder: '.'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: $(AZ_CONN)
    subscriptionId: $(SUB_ID)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(RES_GROUP)
    location: 'uksouth'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.parameters.json'
    overrideParameters: '-vmName "$(VM_NAME)" -adminUsername "$(ADMIN_USER)" -adminPasswordOrKey "$(ADMIN_AUTH)" -authenticationType "$(ADMIN_AUTH_TYPE)" -virtualNetworkName "$(V_NET)" -subnetName "$(SUB_NET)" -dnsLabelPrefix "$(DNS_PREFIX)$(VM_NAME)" -virtualNetworkPrefix "$(V_NET_PREFIX)" -subnetPrefix "$(SUB_NET_PREFIX)" -deployNetwork $(DEPLOY_VNET)'
    deploymentMode: 'Incremental'
    deploymentOutputs: 'sshCommand'

