# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  ADMIN_USER: $(adminUser)
  ADMIN_PASS: $(adminPass)
  VM_NAME: $(vmName)
  V_NET: $(vNet)
  V_NET_PREFIX: $(vNetPrefix)
  SUB_NET: $(subNet)
  SUB_NET_PREFIX: $(subNetPrefix)
  DNS_PRFX: $(dnsLabelPrefix)


trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: CopyFiles@2
  inputs:
    SourceFolder: '.'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: $(azConnection)
    subscriptionId: $(subId)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(resGroup)
    location: 'uksouth'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.parameters.json'
    overrideParameters: '-vmName $(VM_NAME) -adminUsername $(ADMIN_USER) -adminPasswordOrKey $(ADMIN_PASS) -virtualNetworkName $(V_NET) -subnetName $(SUB_NET) -dnsLabelPrefix $(DNS_PRFX) -virtualNetworkPrefix "172.31.0.0/16" -subnetPrefix "172.31.0.0/24"'
    deploymentMode: 'Incremental'
